### PR TITLE
Prevent nepotism with generational GCs

### PR DESCRIPTION
**Pull request by varming**

### CODE REVIEW

**Comment by Scottmitch** [comment]
@varming - I believe the goal is to deprecate this package ... would you be interested in submitting also submitting a PR to Netty?

**Comment by varming** [comment]
Dear Scott Mitchell,

I can take a look at Netty. I patched this library as it is the one used in the application where nepotism has been observed. I still think it is worth committing this patch as this library is currently in use.

**Comment by Scottmitch** [comment]
@varming - Agreed ... patch it here if you are still using this library. Was more curious if you were aware of our previous discussions with the Twitter folks to move to codec-http2 in Netty.

I'll submit a patch for Netty if you are not interested or are not using this fork.

**Comment by varming** [comment]
Dear Scott,

I sent a pull request to Netty as well.

**Pull request merged**
